

export const ADD_NEW_USER_REQUEST="ADD_NEW_USER_REQUEST"
export const ADD_NEW_USER_SUCCESS="ADD_NEW_USER_SUCCESS"
export const ADD_NEW_USER_FAIL="ADD_NEW_USER_FAIL"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOUGOUT="LOUGOUT"

export const GET_USER_DETAILS_REQUEST="GET_USER_DETAILS_REQUEST"
export const GET_USER_DETAILS_SUCCESS="GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAIL="GET_USER_DETAILS_FAIL"